dist: trusty
sudo: false
language: node_js
node_js:
  - "node"
cache: yarn
branches:
  only:
  - master
  - dev
deploy:
  provider: script
  script: ./deploy.sh 5.2.76.53
  skip_cleanup: true
  on:
    branch:
    - dev
before_install:
  - openssl aes-256-cbc -K $encrypted_a1f31b26211c_key -iv $encrypted_a1f31b26211c_iv -in server.enc -out $HOME/.ssh/server -d
